version: "2"

services:
    php-apache:
        build: docker/php-apache
        links:
            - mysql
        volumes:
            - ./src:/var/www/html
        ports:
            - "80:80"

    mysql:
        image: mysql:5.6
        env_file:
            - .env
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "33006:3306"

    adminer:
        image: clue/adminer
        ports:
            - "8080:80"

    mail:
        image: djfarrelly/maildev
        ports:
            - "8081:80"
            - "25:25"

volumes:
    mysql: {}