version: "2"

services:
    apache:
        image: httpd:2.4
        depends_on:
            - php-fpm
            - php-cli
            - mysql
        volumes:
            - ./src:/var/www/html
            - ./docker/apache/vhost.conf:/etc/apache2/sites-avalable/default.conf
        ports:
            - "80:80"

    mysql:
        image: mysql:5.6
        env_file:
            - .env
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "33006:3306"

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html

    php-cli:
        build: docker/php-cli

    adminer:
        image: clue/adminer
        ports:
            - 8080:80

    mail:
        image: djfarrelly/maildev
        ports:
            - 8081:80

volumes:
    mysql: {}
