index:
    path: /
    controller: App\Controller\DefaultController::index

get:
    path: /get/{id}
    controller: App\Controller\DefaultController::get

test: 
    path: /test
    controller: App\Controller\TestController::index
