# Index #
index:
    path: /
    controller: App\Controller\DefaultController::index

create:
    path: /create
    controller: App\Controller\DefaultController::create

forget_password:
    path: /forget/password
    controller: App\Controller\DefaultController::forgetPassword

forget_token:
    path: /forget/token
    controller: App\Controller\DefaultController::forgetToken
    methods: [POST]

forget_check:
    path: /forget/check/{key}
    controller: App\Controller\DefaultController::forgetCheck
    methods: [POST]
#    requirements:
#            key:  \w{5}

# Project #
show_project:
    path: /project/{name}
    controller: App\Controller\ProjectController::showProject

