# Index #
index:
    path: /
    controller: App\Controller\DefaultController::index

create:
    path: /create
    controller: App\Controller\DefaultController::create

forget_password:
    path: /forget/password
    controller: App\Controller\DefaultController::forgetPassword


# Project #
show_project:
    path: /project/{name}
    controller: App\Controller\ProjectController::showProject

